language: android
android:
components:
- tools
- platform-tools
- build-tools-24.0.2
- build-tools-22.0.1
- android-22
env:
global:
before_install:
- echo "Before install stage"
- android list sdk --no-ui --all --extended
install:
- echo "Install stage"
- sudo apt-get install -y python-software-properties
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get update -y
- sudo apt-get install -y nodejs
- sudo npm -g install cordova
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- cordova platform remove android
- cordova platform add android@3.7.1
- cordova build android
after_success:
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
deploy:
provider: releases
api_key:
file: platforms/android/ant-build/MainActivity-debug.apk
on:
tags: true
all_branches: true